// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IIdentity$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IIdentity";
  readonly sourceName: "contracts/IIdentity.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"user","type":"address"}],"name":"hasPassed","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/IIdentity.sol";
  readonly buildInfoId: "solc-0_8_20-74eaeced7999213bd97463715d8bea6814228d2a";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IIdentity"]: IIdentity$Type;
    ["contracts/IIdentity.sol:IIdentity"]: IIdentity$Type;
  }
}